site_name: RataTuring

theme:
  name: material
  language: pt-BR
  features:
      - navigation.tabs

  palette:
    - scheme: slate
      primary: lime
      accent: pink
extra:
  generator: false
plugins: []
repo_name: PI1 - Grupo 02
repo_url: https://github.com/fcte-pi1/2026_1_PI1_Grupo02_Bruno.git
nav:
  - Início: index.md
  - Equipe: pages/equipes.md
  - Cronograma: pages/cronograma/cronograma.md
  - EAP do Projeto: pages/eap/eap.md
  - Documentação:
    - Energia: pages/energia/energia.md
    - Estrutura: pages/estrutura/estrutura.md
    - Hardware: pages/hardware/hardware.md
    - Software: 
      - Arquitetura de Software: pages/software/arquitetura_software.md
  - Entregas:
    - Ponto de Controle 1: 
      - Backlog Priorizado: pages/entregas/pc1/backlog.md
    - Ponto de Controle 2: pages/entregas/pc2.md
    - Ponto de Controle 3: pages/entregas/pc3.md
extra_css:
  - stylesheets/extra.css
exclude_docs: |
  relatorio/
  README.md