
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19108
     no. of nonzeroes in lower triangle of a =          672550
     no. of nonzeroes in the factor l        =         3663408
     ratio of nonzeroes in factor (min/max)  =          0.8062
     number of super nodes                   =             763
     maximum order of a front matrix         =             551
     maximum size of a front matrix          =          152076
     maximum size of a front trapezoid       =          111035
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      8.1894D+08
     no. of floating point ops for solve     =      1.3438D+07
     ratio of flops for factor (min/max)     =          0.6850
     ratio of allocated memory (max/min)     =          1.2568
     number of positive pivots               =           19108
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002737
     time (cpu & wall) for ordering          =        0.031250        0.025820
     time (cpu & wall) for other matrix prep =        0.015625        0.008908
     time (cpu & wall) for value input       =        0.000000        0.002946
     time (cpu & wall) for matrix distrib.   =        0.015625        0.015464
     time (cpu & wall) for numeric factor    =        0.015625        0.038280
     computational rate (gflops) for factor  =       52.412120       21.393456

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         48911.        0. MB
                95-   1         65536.        0. MB         54907.        0. MB
                95-   2         65536.        0. MB         45616.        0. MB
                95-   3         65536.        0. MB         48291.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        262144.        2. MB        197725.        2. MB


  Solver Memory allocated on core    0       =       16.793 MB
  Solver Memory allocated on core    1       =       17.811 MB
  Solver Memory allocated on core    2       =       14.917 MB
  Solver Memory allocated on core    3       =       14.172 MB
  Total Solver Memory allocated by all cores =       63.694 MB

