# Generated by Django 6.0.5 on 2026-05-19 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.IntegerField()),
                ('coluna', models.IntegerField()),
                ('parede_norte', models.CharField(max_length=100)),
                ('parede_sul', models.CharField(max_length=100)),
                ('parede_leste', models.CharField(max_length=100)),
                ('parede_oeste', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_conclusao_sec', models.FloatField(null=True)),
                ('velocidade_med', models.FloatField(null=True)),
                ('consumo_bat', models.FloatField(null=True)),
                ('desafio_concluido', models.BooleanField(default=False)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labirinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.IntegerField()),
                ('nome', models.CharField(max_length=256)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_ordem', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('direcao', models.CharField(max_length=100)),
                ('velocidade', models.FloatField()),
                ('bateria', models.FloatField()),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('celula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetria.celula')),
                ('corrida_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetria.corrida')),
            ],
        ),
        migrations.AddField(
            model_name='corrida',
            name='labitinto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetria.labirinto'),
        ),
        migrations.AddField(
            model_name='celula',
            name='labirinto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetria.labirinto'),
        ),
    ]
